In [1]:
!python -m pytest

============================= test session starts ==============================
platform darwin -- Python 3.6.8, pytest-4.4.1, py-1.8.0, pluggy-0.9.0
rootdir: /Users/dylanpeifer/Documents/programs/deepgroebner
collected 163 items                                                            

tests/test_buchberger.py ............................................... [ 28%]
........................................................................ [ 73%]
.........................                                                [ 88%]
tests/test_hilbert.py .......                                            [ 92%]
tests/test_pg.py ............                                            [100%]

========================== 163 passed in 3.50 seconds ==========================


In [2]:
import numpy as np
import gym

from agents.pg import *
from agents.networks import MultilayerPerceptron

In [3]:
buf = TrajectoryBuffer(0.5, 0.5)
tau = [(np.array([1, 2]), 1, 1, 0),
       (np.array([1, 3]), 0, 1, 0),
       (np.array([1, 4]), 1, 1, 0),
       (np.array([1, 5]), 2, 1, 0),
       (np.array([1, 7]), 0, 1, 0)]
for t in tau:
    buf.store(*t)
buf.finish()
batches = buf.getBatches(lambda s: 3, normalize=False)

In [4]:
states, values, advantages = batches[(2,)]

In [5]:
values

array([[1.9375],
       [1.875 ],
       [1.75  ],
       [1.5   ],
       [1.    ]])

In [6]:
advantages

array([[0.        , 1.33203125, 0.        ],
       [1.328125  , 0.        , 0.        ],
       [0.        , 1.3125    , 0.        ],
       [0.        , 0.        , 1.25      ],
       [1.        , 0.        , 0.        ]])

In [7]:
env = gym.make('CartPole-v0')
policy = MultilayerPerceptron(4, [128], 2, final_activation='softmax')
value = MultilayerPerceptron(4, [128], 1, final_activation='linear')
agent = PGAgent(policy, value_network=value, action_dim_fn=lambda s: 2, value_updates_per_epoch=1)

r = agent.train(env, 100, epochs=20, verbose=1)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Instructions for updating:
Use tf.cast instead.
Epoch: 20/20 - avg_reward: 200.03

In [8]:
r

array([ 22.4 ,  24.97,  31.89,  44.25,  52.97, 109.38, 101.03, 186.26,
       104.77, 200.  , 200.  , 197.86, 183.8 , 199.39, 200.  , 200.  ,
       156.27, 200.  , 198.43, 200.  ])